apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: microservices-gateway
  namespace: default
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: microservices-route
  namespace: default
spec:
  parentRefs:
  - name: microservices-gateway
  rules:
  

  - matches:
    - path:
        type: PathPrefix
        value: /products
    backendRefs:
    - name: productcatalogservice
      port: 3550

 
  - matches:
    - path:
        type: PathPrefix
        value: /cart
    backendRefs:
    - name: cartservice
      port: 7070

 
  - matches:
    - path:
        type: PathPrefix
        value: /currency
    backendRefs:
    - name: currencyservice
      port: 7000

  
  - matches:
    - path:
        type: PathPrefix
        value: /shipping
    backendRefs:
    - name: shippingservice
      port: 50051

  
  - matches:
    - path:
        type: PathPrefix
        value: /recommendations
    backendRefs:
    - name: recommendationservice
      port: 8080

 
  - matches:
    - path:
        type: PathPrefix
        value: /checkout
    backendRefs:
    - name: checkoutservice
      port: 5050


  - matches:
    - path:
        type: PathPrefix
        value: /email
    backendRefs:
    - name: emailservice
      port: 5000

  
  - matches:
    - path:
        type: PathPrefix
        value: /payment
    backendRefs:
    - name: paymentservice
      port: 50051

  
  - matches:
    - path:
        type: PathPrefix
        value: /ads
    backendRefs:
    - name: adservice
      port: 9555

  
  - matches:
    - path:
        type: PathPrefix
        value: /redis
    backendRefs:
    - name: redis-cart
      port: 6379


  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 80
